name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.starmediadev.plugins.territories.Territories
api-version: 1.17
depend: [StarData,StarMCUtils,PlotFramework]